### ISSUE TITLE
Inconsistent build for Helmet.js

### ISSUE THREAD

**Issue by hguillermo** [Schiavi/inferno-helmet#5]
When I build inferno-helmet locally the Helmet.js under lib contains this code (line 420):
```
            value: function render() {
                return createVNode(16, Component, null, null, Object.assign({}, this.props));
            }
```
Which makes sense and works great.

When I do ``npm install inferno-helmet`` the code I can see under node_modules in the same file is:
```
            value: function render() {
                return createVNode(16, Component, Object.assign({}, this.props));
            }
```
Does npm save the generated code? or it "compiles" locally when you do npm install? anyway something is not right. cc @Schiavi

**Comment by hguillermo** [comment]
It seems like npm saves the lib directory which is generated. Maybe you compiled it with some newer node? What version of node did you use?

**Comment by Schiavi** [comment]
Looking into my version, the code that babel generates is that second version. Perhaps there is something different on your local version, something that did not get uploaded by that PR? Could be some error on my side too.

**Comment by hguillermo** [comment]
@Schiavi When I build inferno-helmet locally I can see the first version. Using node 6.9.4. Could you please delete your node_modules and npm i again? Maybe you have old versions of inferno locally? createVNode changed in the newest version.

**Comment by Schiavi** [comment]
There was something wrong with my version, just like you said. I'm compiling with the new version now, and will update the npm package in a few minutes.

**Comment by hguillermo** [comment]
oh perfect! Thanks a lot!

**Comment by Schiavi** [comment]
had to release a new version (4.0.2), but now everything should be OK. Thanks a lot for your help.

**Comment by hguillermo** [comment]
Thanks @Schiavi!
