### ISSUE TITLE
Latest Helmet has an import statement in lib

### ISSUE THREAD

**Issue by mienaikoe** [Schiavi/inferno-helmet#9]
At line 8 in lib/Helmet.js

`import { createComponentVNode, normalizeProps } from "inferno";`

using version 5.2.0

This causes compilation errors in webpack

**Comment by Schiavi** [comment]
Can you elaborate on how to simulate this issue?

I created a new project and installed inferno-helmet, inside node_modules/lib/helmet.js there is no import.

![image](https://user-images.githubusercontent.com/13576166/42694917-462e473a-868a-11e8-904d-7e581d0f94eb.png)

**Comment by mienaikoe** [comment]
The dependency in my package.json is `"inferno-helmet": "^5.2.0"`

I just installed with `npm install`

![screen shot 2018-07-13 at 10 22 43 am](https://user-images.githubusercontent.com/3875239/42696623-bc8e30c4-8686-11e8-8146-edc529f63ed3.png)

Have seen this happen on two machines.

**Comment by Schiavi** [comment]
Hello! 

I updated the package to not use the import. But looking into it I found out that it is by default from [babel-plugin-inferno](https://github.com/infernojs/babel-plugin-inferno#imports-boolean). You should try to update webpack on your project to use Inferno.

For now you can update inferno-helmet to version 5.2.1.

Good luck!

**Comment by mienaikoe** [comment]
Hm. Not sure what you mean by "update webpack on your project to use Inferno."

I am using both Webpack and inferno just fine. None of the packages I use for inferno had this problem. Just inferno-helmet.

5.2.1 works
